"""initial commit 3

Revision ID: 0a0ceda3accb
Revises: d38d79e17c5a
Create Date: 2024-03-07 19:57:00.128326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a0ceda3accb"
down_revision: Union[str, None] = "d38d79e17c5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profiles_user_id_fkey", "profiles", type_="foreignkey")
    op.drop_column("profiles", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "profiles_user_id_fkey", "profiles", "users", ["user_id"], ["user_id"]
    )
    # ### end Alembic commands ###
