"""drop tables

Revision ID: a200666ee461
Revises: 83f0557c78d6
Create Date: 2024-04-14 18:44:42.326839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a200666ee461"
down_revision: Union[str, None] = "83f0557c78d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interests")
    op.drop_table("profiles")
    op.create_unique_constraint(None, "user_logins", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "user_logins", type_="unique")
    op.create_table(
        "profiles",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "first_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("gender", sa.VARCHAR(length=2), autoincrement=False, nullable=False),
        sa.Column("show_me", sa.VARCHAR(length=2), autoincrement=False, nullable=False),
        sa.Column("date_of_birth", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column(
            "country", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("city", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="profiles_pkey"),
    )
    op.create_table(
        "interests",
        sa.Column("interest_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("interest_id", name="interests_pkey"),
        sa.UniqueConstraint("title", name="interests_title_key"),
    )
    # ### end Alembic commands ###
