"""initial commit 2

Revision ID: d38d79e17c5a
Revises: eabfc328d3e1
Create Date: 2024-03-07 19:54:40.912251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d38d79e17c5a"
down_revision: Union[str, None] = "eabfc328d3e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("user_interests")
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_table(
        "user_interests",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("interest_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interests.interest_id"],
            name="user_interests_interest_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name="user_interests_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("user_id", "interest_id", name="user_interests_pkey"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.role_id"], name="user_roles_role_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name="user_roles_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name="user_roles_pkey"),
    )
    # ### end Alembic commands ###
